# Generated by Django 5.2 on 2025-04-21 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('date_imported', models.DateTimeField(auto_now_add=True)),
                ('successful_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Import History',
                'verbose_name_plural': 'Import Histories',
                'ordering': ['-date_imported'],
            },
        ),
        migrations.CreateModel(
            name='Landscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the landscape', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Description of the landscape')),
                ('image_url', models.URLField(help_text='URL of the landscape image', max_length=1000, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landscape',
                'verbose_name_plural': 'Landscapes',
                'ordering': ['-created_at'],
            },
        ),
    ]
